### PR TITLE
Updating time worked

### PR DESCRIPTION
**Pull request by georgemarks**
Time spent towards setting up local development and running server

### CODE REVIEW

**Comment by JohnLockwood** [comment]
There were conflicts with lines I added, so I'll add the lines manually.  Thanks George.

**Comment by georgemarks** [comment]
The other day I was re-reading your last email. You mentioned about adding
me to the CodeSolid site that I've joined the development effort. This
makes sense. Sorry I didn't this question earlier.

**Comment by georgemarks** [comment]
Using GitHub how do you resolve the merge conflict? Is it don't from within
GitHub?

**Comment by JohnLockwood** [comment]
No, but the merge conflict for resolving the conflict will give you
instructions for resolving it at the command line.  It wasn't too hard.
Since you're dealing with a fork, it looks like you'll need to do this from
time to time as well to sync up:
https://help.github.com/articles/syncing-a-fork/.  Saw your email about
future work -- sounds good.  I think the structure of hours.json is such
that we'll get conflicts all the time so we might think about splitting out
files.  Really this is just temporary until we can figure out how to keep
the database all good in production and have enough confidence to track it
there.

John Lockwood
Employee Owner at CodeSolid
http://www.codesolid.com
916-359-9218

**Pull request merged**
